### ISSUE TITLE
Reference Error when running on Node.js

### ISSUE THREAD

**Issue by chasemccoy** [github/details-menu-element#5]
I am using this package on a React site using [Compositor's x0](https://compositor.io/x0/). When building the site to static files, I get the following error:

```
building static sitewebpack:///./node_modules/@github/details-menu-element/dist/index.esm.js?:15
Object.setPrototypeOf(_CustomElement.prototype, HTMLElement.prototype);
                                                ^

ReferenceError: HTMLElement is not defined
    at eval (webpack:///./node_modules/@github/details-menu-element/dist/index.esm.js?:15:49)
    at Module../node_modules/@github/details-menu-element/dist/index.esm.js (/Users/chasemccoy/Repositories/playground/dist/TEMP/App.js:323:1)
    at __webpack_require__ (/Users/chasemccoy/Repositories/playground/dist/TEMP/App.js:30:30)
    at eval (webpack:///./src/details/index.mdx?:14:1)
    at Object../src/details/index.mdx (/Users/chasemccoy/Repositories/playground/dist/TEMP/App.js:5981:1)
    at __webpack_require__ (/Users/chasemccoy/Repositories/playground/dist/TEMP/App.js:30:30)
    at webpackContext (webpack:///./src_sync_\.(js%7Cmd%7Cmdx%7Cjsx)$?:18:9)
    at eval (webpack:///./node_modules/@compositor/x0/src/entry.js?:116:15)
    at Array.map (<anonymous>)
    at getComponents (webpack:///./node_modules/@compositor/x0/src/entry.js?:112:6)
```

From what I can tell, this has to do with the `HTMLElement` object not being present outside of the browser. Is there anything that can be done to this package to support server rendering? If not, is there a way I can work around this?

**Comment by dgraham** [comment]
The custom element code should be included in the `.js` bundle served to the browser rather than loaded and executed on the server. If you were to run on a server, you would need to load a DOM environment with Web Components support, like https://github.com/jsdom/jsdom/issues/1030.
